git:
  depth: 2
  quiet: true
os:
  - linux
  - osx
install:
  - source install_conda.sh
  - conda install anaconda-client -n base
script:
  - conda env create mmwarowny/compbio-services
  - conda activate compbio-services
  - slivka --version | grep -q '0.6'
  - command -v slivka-bio
